### ISSUE TITLE
A *todo* list of many "minor" changes (with big impact)

### ISSUE THREAD

**Issue by AlexandreDecan** [AlexandreDecan/sismic#24]
The main idea behind this quite huge refactoring is to separate the structure of a statechart from its content. The idea is to put the structural information of a statechart in a ``Statechart`` instance, and to make use of the other classes as data class. 
This way, it will be a lot easier to construct and manipulate a statechart "in memory" (in contrast to its import from a YAML document). 

These changes will help us to do statechart transformations and to implement a nice UI to create or edit statecharts. 

## Exceptions
Define a proper hierarchy of exceptions that are raised by Sismic (see #22  for the motivation).  
Those exceptions will be available in ``sismic.exceptions``:
 - [x] A ``SismicError`` base exception at the top of the hierarchy. 
 - [x] A base ``InvalidStatechartError``
 - [x] A ``CodeEvaluationError`` (raised by a ``code.PythonEvaluator`` from any exception raised by ``exec`` or ``eval``). 
 - [x] A base ``ExecutionError``and that is extended by ``NonDeterminismError`` and ``ConflictingTransitionsError`` (both raised by ``Interpreter._sort_transitions``)
 - [x] A base ``ContractError`` (currently ``ConditionFailed``) that is extended by ``InvariantError`` (currently ``InvariantFailedException``), ``PreconditionError`` (currently ``PreconditionFailed``) and ``Postcondition`` (currently ``PostconditionFailed``). 

## Transitions
 - [x] A ``Transition`` instance should not store an ``Event`` object, just its name.
 - [x] The ``from_state`` and ``to_state`` of a transition should be made protected, and ``from_state`` and ``to_state`` properties should be made available. 

## Mixins
 - [x] Make ``StateMixin.name`` protected and add a ``StateMixin.name`` property on it.
 - [x] A ``CompositeStateMixin`` should not record its children. This information should be stored in a ``Statechart`` instance (as we currently do it for ``parent``). 
 - [x] ``TransitionStateMixin`` should not store data about transitions, and should be a class whose purpose is only for type checking. 
 - [x] Add a ``RootState`` which inherits from ``ContractMixin``, ``StateMixin``, ``ActionStateMixin``, ``CompositeStateMixin``.

## YAML
 - [x] Add a *context* key on *statechart* element which has the semantic of the actual *on entry*. 

## Statechart
 - [x] The ``Statechart`` class should not anymore inherit from any subclass of ``StateMixin``. Instances of ``Statechart`` should be created with a ``root`` parameter which has to be a ``RootState`` (it is the only state that has no parent).
 - [x] The constructor of a ``Statechart`` should accept an optional ``description`` parameter to be consistent with its YAML representation.

### Statechart states
 - [x] Add a ``state_for`` function that is a mapping from name to ``StateMixin`` instances. 
 - [x] Add a ``parent_for`` and a ``children_for`` methods that take a ``StateMixin`` or a name and returns ``StateMixin`` instances.
 - [x] Add a ``children_for`` that accepts a ``StateMixin`` or a name and returns its children instances, if any.
 - [x] Add a ``states`` property that returns a list of ``StateMixin``. 
 - [x] Add an ``add_state`` which takes a ``StateMixin`` and a ``parent`` (name or ``StateMixin``) parameter. It should ensures that a state with the same name does not exist (raises ``InvalidStatechartError``), and that given ``parent`` accepts child states (raises ``InvalidStatechartError``). If added state is an ``HistoryState``, its parent must be a ``CompoundState`` (raises ``InvalidStatechartError``, check C2). 
 - [x] A ``remove_state`` which takes a name or ``StateMixin`` and remove it. The removal can be done only if the state has no more children and no more (outgoing or incoming) transitions.

### Statechart transitions
 - [x] Use a ``transitions`` property that returns a list of ``Transition`` instances.
 - [x] Add an ``add_transition`` which takes a ``Transition`` instance. The method checks that source state is a ``TransitionStateMixin`` and that target state exists.
 - [x] Add ``transitions_from`` and ``transitions_to`` that take a ``StateMixin`` or a name and return a list of transitions. 
 - [x] Add a ``transitions_with`` that takes an event name or an ``Event`` instance and returns a list of transitions. 
 - [x] A ``remove_transition`` that takes a ``Transition`` instance and remove it. 

### Statechart utils
 - [x] Adapt ``descendants_for``, ``ancestors_for``, ``leaf_for``, ``depth_of`` (rename it ``depth_for`` to be consistent), ``least_common_ancestor``, etc. such that these methods accept either a name or a ``StateMixin``. These methods should return ``StateMixin`` instances. 
 - [x] Remove the ``@lru_cache`` or invalidate this cache when a change occurs in the statechart.

### Statechart validation
 - [x] Checks C1 to C6 should raise ``InvalidStatechartError`` with a ``code`` attribute reflecting the check that failed. Notice that C1 and C2 are already checked during construction. 

## IO
 - [x] ``import_from_yaml`` and ``export_to_yaml`` must support the new YAML keys and the new exceptions hierarchy.

## Interpreter
 - [x] The configuration of an ``Interpreter`` instance now always contains the root state, except if it is in a final (ie. empty) configuration.
 - [x] The configuration contains ``StateMixin`` instead of names.

## Documentation
 - Adapt the documentation for the new YAML format (*context* key)
 - Adapt the examples (both in the documentation AND in its subdirectory *examples*)
 - Adapt the documentation for the "design by contract" (as there is no more a different behaviour for contracts of a statechart and contracts for a state. The "old" contracts for a statechart are now the "new" contracts for its root state). 

(The list will be completed as soon as ideas come)

**Comment by AlexandreDecan** [comment]
Most changes are now implemented (currently not uploaded). 
Main differences between the implementation and the todo list is that we still rely on "state name" instead of "state object" for a majority of Statechart's methods.
